// <auto-generated />
using System;
using Licenses.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Licenses.Migrations
{
    [DbContext(typeof(LicensesContext))]
    [Migration("20260525103741_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Licenses.Models.ActivityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ActivityTypes");
                });

            modelBuilder.Entity("Licenses.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Licenses.Models.ExcutivePosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExcutivePositions");
                });

            modelBuilder.Entity("Licenses.Models.Fees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CollectionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("FeesTypes")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("TransactionLotOrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TransactionLotOrderId");

                    b.ToTable("Fees");
                });

            modelBuilder.Entity("Licenses.Models.Lot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityTypeId")
                        .HasColumnType("int");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExcutivePositionId")
                        .HasColumnType("int");

                    b.Property<int>("FileNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LotNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NeighborhoodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityTypeId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ExcutivePositionId");

                    b.HasIndex("LotNum", "AreaName", "NeighborhoodName")
                        .IsUnique();

                    b.ToTable("Lots");
                });

            modelBuilder.Entity("Licenses.Models.LotOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("ContractDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LotId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartWorkingDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("LotId");

                    b.HasIndex("OrderId");

                    b.ToTable("LotOrders");
                });

            modelBuilder.Entity("Licenses.Models.LotOrderSteps", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndingDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LotOrderId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartingDate")
                        .HasColumnType("date");

                    b.Property<int>("StepOrderId")
                        .HasColumnType("int");

                    b.Property<int>("StepStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LotOrderId");

                    b.HasIndex("StepOrderId");

                    b.ToTable("LotOrdersSteps");
                });

            modelBuilder.Entity("Licenses.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Licenses.Models.OrderSteps", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("StepId")
                        .HasColumnType("int");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("StepId");

                    b.HasIndex("StepNumber")
                        .IsUnique();

                    b.ToTable("OrderSteps");
                });

            modelBuilder.Entity("Licenses.Models.Stage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stages");
                });

            modelBuilder.Entity("Licenses.Models.Step", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Steps");
                });

            modelBuilder.Entity("Licenses.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Licenses.Models.TransactionLotOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LotOrderId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TransactionStagesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LotOrderId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("TransactionNumber")
                        .IsUnique();

                    b.HasIndex("TransactionStagesId");

                    b.ToTable("TransactionLotOrders");
                });

            modelBuilder.Entity("Licenses.Models.TransactionLotOrderStages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndingDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartingDate")
                        .HasColumnType("date");

                    b.Property<int>("StepStatus")
                        .HasColumnType("int");

                    b.Property<int>("TransactionLotOrderId")
                        .HasColumnType("int");

                    b.Property<int>("TransactionStagesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TransactionLotOrderId");

                    b.HasIndex("TransactionStagesId");

                    b.ToTable("TransactionLotOrderStages");
                });

            modelBuilder.Entity("Licenses.Models.TransactionStages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.Property<int>("StageNumber")
                        .HasColumnType("int");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.HasIndex("StageNumber")
                        .IsUnique();

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionStages");
                });

            modelBuilder.Entity("Licenses.Models.Fees", b =>
                {
                    b.HasOne("Licenses.Models.TransactionLotOrder", "TransactionLotOrder")
                        .WithMany("Fees")
                        .HasForeignKey("TransactionLotOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransactionLotOrder");
                });

            modelBuilder.Entity("Licenses.Models.Lot", b =>
                {
                    b.HasOne("Licenses.Models.ActivityType", "ActivityType")
                        .WithMany("Lots")
                        .HasForeignKey("ActivityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Licenses.Models.Client", "Client")
                        .WithMany("Lots")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Licenses.Models.ExcutivePosition", "ExcutivePosition")
                        .WithMany("Lots")
                        .HasForeignKey("ExcutivePositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityType");

                    b.Navigation("Client");

                    b.Navigation("ExcutivePosition");
                });

            modelBuilder.Entity("Licenses.Models.LotOrder", b =>
                {
                    b.HasOne("Licenses.Models.Lot", "Lot")
                        .WithMany("LotOrders")
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Licenses.Models.Order", "Order")
                        .WithMany("LotOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lot");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Licenses.Models.LotOrderSteps", b =>
                {
                    b.HasOne("Licenses.Models.LotOrder", "LotOrder")
                        .WithMany()
                        .HasForeignKey("LotOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Licenses.Models.OrderSteps", "OrderSteps")
                        .WithMany("LotOrderSteps")
                        .HasForeignKey("StepOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LotOrder");

                    b.Navigation("OrderSteps");
                });

            modelBuilder.Entity("Licenses.Models.OrderSteps", b =>
                {
                    b.HasOne("Licenses.Models.Order", "Order")
                        .WithMany("OrderSteps")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Licenses.Models.Step", "Step")
                        .WithMany("OrderSteps")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Step");
                });

            modelBuilder.Entity("Licenses.Models.Transaction", b =>
                {
                    b.HasOne("Licenses.Models.Order", "Order")
                        .WithMany("Transactions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Licenses.Models.TransactionLotOrder", b =>
                {
                    b.HasOne("Licenses.Models.LotOrder", "LotOrder")
                        .WithMany("TransactionLotOrders")
                        .HasForeignKey("LotOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Licenses.Models.Transaction", null)
                        .WithMany("TransactionLotOrders")
                        .HasForeignKey("TransactionId");

                    b.HasOne("Licenses.Models.TransactionStages", "TransactionStages")
                        .WithMany()
                        .HasForeignKey("TransactionStagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LotOrder");

                    b.Navigation("TransactionStages");
                });

            modelBuilder.Entity("Licenses.Models.TransactionLotOrderStages", b =>
                {
                    b.HasOne("Licenses.Models.TransactionLotOrder", "TransactionLotOrder")
                        .WithMany("TransactionLotOrderStages")
                        .HasForeignKey("TransactionLotOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Licenses.Models.TransactionStages", "TransactionStages")
                        .WithMany("TransactionLotOrderStages")
                        .HasForeignKey("TransactionStagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransactionLotOrder");

                    b.Navigation("TransactionStages");
                });

            modelBuilder.Entity("Licenses.Models.TransactionStages", b =>
                {
                    b.HasOne("Licenses.Models.Stage", "Stage")
                        .WithMany("TransactionStages")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Licenses.Models.Transaction", "Transaction")
                        .WithMany("TransactionStages")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stage");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Licenses.Models.ActivityType", b =>
                {
                    b.Navigation("Lots");
                });

            modelBuilder.Entity("Licenses.Models.Client", b =>
                {
                    b.Navigation("Lots");
                });

            modelBuilder.Entity("Licenses.Models.ExcutivePosition", b =>
                {
                    b.Navigation("Lots");
                });

            modelBuilder.Entity("Licenses.Models.Lot", b =>
                {
                    b.Navigation("LotOrders");
                });

            modelBuilder.Entity("Licenses.Models.LotOrder", b =>
                {
                    b.Navigation("TransactionLotOrders");
                });

            modelBuilder.Entity("Licenses.Models.Order", b =>
                {
                    b.Navigation("LotOrders");

                    b.Navigation("OrderSteps");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Licenses.Models.OrderSteps", b =>
                {
                    b.Navigation("LotOrderSteps");
                });

            modelBuilder.Entity("Licenses.Models.Stage", b =>
                {
                    b.Navigation("TransactionStages");
                });

            modelBuilder.Entity("Licenses.Models.Step", b =>
                {
                    b.Navigation("OrderSteps");
                });

            modelBuilder.Entity("Licenses.Models.Transaction", b =>
                {
                    b.Navigation("TransactionLotOrders");

                    b.Navigation("TransactionStages");
                });

            modelBuilder.Entity("Licenses.Models.TransactionLotOrder", b =>
                {
                    b.Navigation("Fees");

                    b.Navigation("TransactionLotOrderStages");
                });

            modelBuilder.Entity("Licenses.Models.TransactionStages", b =>
                {
                    b.Navigation("TransactionLotOrderStages");
                });
#pragma warning restore 612, 618
        }
    }
}
